# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

rbs:
  ruby: circleci/ruby@2.0.0

commands:
  build-ios-app:
    steps:
      - attach_workspace:
          at: /tmp/build_space/
      - run:
          name: bundle install
          command: |-
            echo "code: ruby --version"
            ruby --version

jobs:
  pre-build:
    docker:
      - image: cimg/ruby:3.2.2-node
    steps:
      - run: mkdir build_space
      - checkout:
          path: /tmp/build_space/git_repo
      - persist_to_workspace:
          root: /tmp/build_space
          paths:
            - git_repo

  build-consumer-ios-app-prod:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    working_directory: /tmp/build_space/git_repo
    steps:
      - attach_workspace:
          at: /tmp/build_space/
      - build-ios-app

workflows:
  build-things:
    jobs:
      - pre-build
      - build-consumer-ios-app-prod
