# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  #ruby: circleci/ruby@2.0.0
  #macos: circleci/macos@2.3.6

commands:
  build-ios-app:
    steps:
      - attach_workspace:
          at: /tmp/build_space/
      - macos/switch-ruby:
          version: "2.7.5"
      - run:
          name: bundle install
          command: |-
            echo "code: ruby --version"
            ruby --version

jobs:
  pre-build:
    steps:
      - run: mkdir build_space
      - checkout:
          path: /tmp/build_space/git_repo
      - persist_to_workspace:
          root: /tmp/build_space
          paths:
            - git_repo

  build-consumer-ios-app-prod:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    working_directory: /tmp/build_space/git_repo
    steps:
      - attach_workspace:
          at: /tmp/build_space/
      - build-ios-app

workflows:
  build-things:
    jobs:
      #- pre-build
      - build-consumer-ios-app-prod
