# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

commands:
  build-ios-app:
    steps:
      - attach_workspace:
          at: /tmp/build_space/
      - run:
          name: bundle install
          command: |-
            echo "code: curl -sSL..."
            curl -sSL https://get.rvm.io | bash
            echo "code: source ~..."
            source ~/.rvm/scripts/rvm
            echo "code: rvm install 3.2.2..."
            rvm install 3.2.2
            echo "code: rvm use default 3.2.2"
            rvm use default 3.2.2
            echo "code: cd $APP_FOLDER"
            cd $APP_FOLDER
            echo "code: bundle install"
            bundle install
            echo "code: type rvm | head -1"
            type rvm | head -1

jobs:
  build-consumer-ios-app-prod:
    macos:
      xcode: 15.0.0
    resource_class: macos.x86.medium.gen2
    working_directory: /tmp/build_space/git_repo
    steps:
      - attach_workspace:
          at: /tmp/build_space/
      - build-ios-app

  build-orb:
    steps:
      - checkout
      - ruby/install:
          version: '2.7'
      - run: echo "Ruby 2.7 has been installed"

workflows:
  build-things:
    jobs:
      #- build-consumer-ios-app-prod
      - build-orb
